services:
  backend-base:
    build: ./SpringBackend
    depends_on:
      - db
    ports:
      - "3000:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "4000:3306"

    volumes:
      - db_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  # frontend:
  #   build: ./NextFrontend

volumes:
  db_data:
